
package view.employee;

import java.awt.geom.RoundRectangle2D;

import model.Accounts;
import model.Customers;
import control.AccountsControl;
import control.CustomersControl;
import java.awt.Color;
import java.awt.Font;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javaswingdev.swing.table.TableHeader;
import javax.swing.JOptionPane;
import table.TableCustomers;
import javax.swing.table.TableModel;
import table.TableAccounts;

public class CustomerServiceView extends javax.swing.JFrame {
    AccountsControl accountControl;
    CustomersControl customerControl;
    String action = null;
    int selectedIdAccount = 0;
    int selectedIdCustomer = 0;
    /**
     * Creates new form CustomerServiceView
     */
    public CustomerServiceView() {
        initComponents();
        customerControl = new CustomersControl();
        accountControl = new AccountsControl();
        setComponent(false);
        setEditDeleteBtn(false);
        showAccounts();
        init();
        initJFrame();
    }
    
    
    public void initJFrame(){
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }
    
    public void init(){
        titleBar.initJFram(this);
    }
    
    public void setComponent(boolean value){
        inputFirstName.setEnabled(value);
        inputLastName.setEnabled(value);
        inputEmail.setEnabled(value);
        inputPhoneNumber.setEnabled(value);
        inputAddress.setEnabled(value);
        
        inputUsername.setEnabled(value);
        inputPassword.setEnabled(value);
        inputBalance.setEnabled(value);
        accountTypeComboBox.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void clearText(){
        inputFirstName.setText("");
        inputLastName.setText("");
        inputEmail.setText("");
        inputPhoneNumber.setText("");
        inputAddress.setText("");
        
        inputUsername.setText("");
        inputPassword.setText("");
        inputBalance.setText("");
        accountTypeComboBox.setSelectedItem(ABORT);
    }
    
    public void setEditDeleteBtn(boolean value){
        deleteBtn.setEnabled(value);
        editBtn.setEnabled(value);

    }
    public void setAddBtn(boolean value){
        addBtn.setEnabled(value);
    }
    
    public void showAccounts(){
        tableCustomers.getTableHeader().setFont(new Font("Montserrat", Font.PLAIN, 12));
        tableCustomers.getTableHeader().setOpaque(false);
        tableCustomers.getTableHeader().setForeground(new Color(0, 61, 121));
        tableCustomers.setRowHeight(25);
        tableCustomers.setModel( accountControl.showTableAccounts(""));
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        labelPane = new javax.swing.JLabel();
        titleBar = new javaswingdev.swing.titlebar.TitleBar();
        jLabel1 = new javax.swing.JLabel();
        baseInputCus = new view.PanelRound();
        firstNameLabel = new javax.swing.JLabel();
        inputFirstName = new javax.swing.JTextField();
        lastNameLabel = new javax.swing.JLabel();
        inputLastName = new javax.swing.JTextField();
        emailLabel = new javax.swing.JLabel();
        inputEmail = new javax.swing.JTextField();
        phoneNumberLabel = new javax.swing.JLabel();
        inputPhoneNumber = new javax.swing.JTextField();
        addressLabel = new javax.swing.JLabel();
        inputAddress = new javax.swing.JTextField();
        password = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        inputUsername = new javax.swing.JTextField();
        username = new javax.swing.JLabel();
        inputBalance = new javax.swing.JTextField();
        balanceLabel = new javax.swing.JLabel();
        accountTypeLabel = new javax.swing.JLabel();
        accountTypeComboBox = new javax.swing.JComboBox<>();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        labelCus = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        labelAcc = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        backgroundTable = new view.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableCustomers = new javax.swing.JTable();
        inputSearch = new javax.swing.JTextField();
        searchBtn = new view.PanelRound();
        labelDelete1 = new javax.swing.JLabel();
        addBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        base.setBackground(new java.awt.Color(245, 245, 245));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 73, 178));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 149, 182));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1440, 122));

        labelPane.setBackground(new java.awt.Color(255, 255, 255));
        labelPane.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 48)); // NOI18N
        labelPane.setForeground(new java.awt.Color(255, 255, 255));
        labelPane.setText("Customer Service");

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/help-desk.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(labelPane)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPane)
                        .addGap(20, 20, 20))))
        );

        baseInputCus.setBackground(new java.awt.Color(255, 255, 255));
        baseInputCus.setPreferredSize(new java.awt.Dimension(285, 100));
        baseInputCus.setRoundBottomLeft(20);
        baseInputCus.setRoundBottomRight(20);
        baseInputCus.setRoundTopLeft(20);
        baseInputCus.setRoundTopRight(20);

        firstNameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        firstNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        firstNameLabel.setText("First Name");

        inputFirstName.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputFirstName.setForeground(new java.awt.Color(0, 0, 0));
        inputFirstName.setNextFocusableComponent(inputLastName);
        inputFirstName.setPreferredSize(new java.awt.Dimension(64, 27));
        inputFirstName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputFirstNameActionPerformed(evt);
            }
        });

        lastNameLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        lastNameLabel.setForeground(new java.awt.Color(51, 51, 51));
        lastNameLabel.setText("Last Name");

        inputLastName.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputLastName.setForeground(new java.awt.Color(0, 0, 0));
        inputLastName.setNextFocusableComponent(inputEmail);
        inputLastName.setPreferredSize(new java.awt.Dimension(64, 27));
        inputLastName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputLastNameActionPerformed(evt);
            }
        });

        emailLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        emailLabel.setForeground(new java.awt.Color(51, 51, 51));
        emailLabel.setText("Email");

        inputEmail.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputEmail.setForeground(new java.awt.Color(0, 0, 0));
        inputEmail.setNextFocusableComponent(inputPhoneNumber);
        inputEmail.setPreferredSize(new java.awt.Dimension(64, 27));

        phoneNumberLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        phoneNumberLabel.setForeground(new java.awt.Color(51, 51, 51));
        phoneNumberLabel.setText("Phone Number");

        inputPhoneNumber.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputPhoneNumber.setForeground(new java.awt.Color(0, 0, 0));
        inputPhoneNumber.setNextFocusableComponent(inputAddress);
        inputPhoneNumber.setPreferredSize(new java.awt.Dimension(64, 27));

        addressLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        addressLabel.setForeground(new java.awt.Color(51, 51, 51));
        addressLabel.setText("Address");

        inputAddress.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputAddress.setForeground(new java.awt.Color(0, 0, 0));
        inputAddress.setPreferredSize(new java.awt.Dimension(64, 27));

        password.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        password.setForeground(new java.awt.Color(51, 51, 51));
        password.setText("Password");

        inputPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputPasswordActionPerformed(evt);
            }
        });

        inputUsername.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputUsername.setForeground(new java.awt.Color(0, 0, 0));
        inputUsername.setPreferredSize(new java.awt.Dimension(64, 27));

        username.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        username.setForeground(new java.awt.Color(51, 51, 51));
        username.setText("Username");

        inputBalance.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        inputBalance.setForeground(new java.awt.Color(0, 0, 0));
        inputBalance.setPreferredSize(new java.awt.Dimension(64, 27));

        balanceLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        balanceLabel.setForeground(new java.awt.Color(51, 51, 51));
        balanceLabel.setText("Balance");

        accountTypeLabel.setFont(new java.awt.Font("Montserrat SemiBold", 1, 14)); // NOI18N
        accountTypeLabel.setForeground(new java.awt.Color(51, 51, 51));
        accountTypeLabel.setText("Account Type");

        accountTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Silver", "Gold", "Platinum", "Titanium", "Spesial" }));
        accountTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accountTypeComboBoxActionPerformed(evt);
            }
        });

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-save.png"))); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-cancel.png"))); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        labelCus.setBackground(new java.awt.Color(51, 51, 51));
        labelCus.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        labelCus.setForeground(new java.awt.Color(0, 61, 121));
        labelCus.setText("Data Customer");

        jPanel1.setBackground(new java.awt.Color(255, 183, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        labelAcc.setBackground(new java.awt.Color(255, 255, 255));
        labelAcc.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        labelAcc.setForeground(new java.awt.Color(0, 61, 121));
        labelAcc.setText("Data Account");

        jPanel2.setBackground(new java.awt.Color(255, 183, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout baseInputCusLayout = new javax.swing.GroupLayout(baseInputCus);
        baseInputCus.setLayout(baseInputCusLayout);
        baseInputCusLayout.setHorizontalGroup(
            baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseInputCusLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseInputCusLayout.createSequentialGroup()
                        .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(username)
                            .addComponent(password)
                            .addComponent(balanceLabel)
                            .addComponent(accountTypeLabel))
                        .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baseInputCusLayout.createSequentialGroup()
                                .addGap(51, 51, 51)
                                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseInputCusLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(accountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(baseInputCusLayout.createSequentialGroup()
                        .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labelCus)
                            .addGroup(baseInputCusLayout.createSequentialGroup()
                                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(firstNameLabel)
                                    .addComponent(lastNameLabel)
                                    .addComponent(emailLabel)
                                    .addComponent(phoneNumberLabel)
                                    .addComponent(addressLabel))
                                .addGap(34, 34, 34)
                                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(inputPhoneNumber, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputEmail, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputLastName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputAddress, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputFirstName, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelAcc)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(35, Short.MAX_VALUE))
        );
        baseInputCusLayout.setVerticalGroup(
            baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseInputCusLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(labelCus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(firstNameLabel)
                    .addComponent(inputFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastNameLabel)
                    .addComponent(inputLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(emailLabel)
                    .addComponent(inputEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(phoneNumberLabel)
                    .addComponent(inputPhoneNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addressLabel)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addComponent(labelAcc)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(username)
                    .addComponent(inputUsername, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(password)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(balanceLabel)
                    .addComponent(inputBalance, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(accountTypeLabel)
                    .addComponent(accountTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(baseInputCusLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );

        backgroundTable.setBackground(new java.awt.Color(255, 255, 255));
        backgroundTable.setPreferredSize(new java.awt.Dimension(285, 100));
        backgroundTable.setRoundBottomLeft(20);
        backgroundTable.setRoundBottomRight(20);
        backgroundTable.setRoundTopLeft(20);
        backgroundTable.setRoundTopRight(20);
        backgroundTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundTableMouseClicked(evt);
            }
        });

        tableCustomers.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableCustomers.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCustomersMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableCustomers);

        javax.swing.GroupLayout backgroundTableLayout = new javax.swing.GroupLayout(backgroundTable);
        backgroundTable.setLayout(backgroundTableLayout);
        backgroundTableLayout.setHorizontalGroup(
            backgroundTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTableLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 778, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(35, Short.MAX_VALUE))
        );
        backgroundTableLayout.setVerticalGroup(
            backgroundTableLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundTableLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 453, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        inputSearch.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                inputSearchMouseClicked(evt);
            }
        });

        searchBtn.setBackground(new java.awt.Color(153, 89, 222));
        searchBtn.setPreferredSize(new java.awt.Dimension(285, 100));
        searchBtn.setRoundBottomLeft(20);
        searchBtn.setRoundBottomRight(20);
        searchBtn.setRoundTopLeft(20);
        searchBtn.setRoundTopRight(20);
        searchBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchBtnMouseClicked(evt);
            }
        });
        searchBtn.setLayout(null);

        labelDelete1.setBackground(new java.awt.Color(255, 255, 255));
        labelDelete1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 14)); // NOI18N
        labelDelete1.setForeground(new java.awt.Color(255, 255, 255));
        labelDelete1.setText("Cari");
        searchBtn.add(labelDelete1);
        labelDelete1.setBounds(23, 6, 29, 18);

        addBtn.setBackground(new java.awt.Color(0, 61, 121));
        addBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setText("Tambah");
        addBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBtnMouseClicked(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(255, 183, 0));
        editBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setText("Ubah");
        editBtn.setNextFocusableComponent(baseInputCus);
        editBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editBtnMouseClicked(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(220, 53, 69));
        deleteBtn.setFont(new java.awt.Font("Montserrat SemiBold", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setText("Hapus");
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baseInputCus, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                        .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 290, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(backgroundTable, javax.swing.GroupLayout.PREFERRED_SIZE, 843, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(46, Short.MAX_VALUE))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(searchBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(baseInputCus, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE)
                    .addComponent(backgroundTable, javax.swing.GroupLayout.DEFAULT_SIZE, 505, Short.MAX_VALUE))
                .addGap(0, 35, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tableCustomersMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCustomersMouseClicked
        setEditDeleteBtn(true);
        setComponent(false);
        setAddBtn(false);
        cancelBtn.setEnabled(true);

        int clickedRow = tableCustomers.getSelectedRow();
        TableModel tableModel = tableCustomers.getModel();

        selectedIdAccount = Integer.parseInt(tableModel.getValueAt(clickedRow,0).toString());
        selectedIdCustomer = Integer.parseInt(tableModel.getValueAt(clickedRow,1).toString());

        inputFirstName.setText(tableModel.getValueAt(clickedRow,2).toString());
        inputLastName.setText(tableModel.getValueAt(clickedRow,3).toString());
        accountTypeComboBox.setSelectedItem(tableModel.getValueAt(clickedRow,4).toString());
        inputBalance.setText(tableModel.getValueAt(clickedRow,5).toString());
        inputEmail.setText(tableModel.getValueAt(clickedRow,6).toString());
        inputPhoneNumber.setText(tableModel.getValueAt(clickedRow,7).toString());
        inputAddress.setText(tableModel.getValueAt(clickedRow,8).toString());
        inputUsername.setText(tableModel.getValueAt(clickedRow,9).toString());
        inputPassword.setText(tableModel.getValueAt(clickedRow,10).toString());
    }//GEN-LAST:event_tableCustomersMouseClicked

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        setComponent(false);
        setEditDeleteBtn(false);
        setAddBtn(true);
        clearText();
        inputSearch.setText("");
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Apakah menambah data transfer?", "Konfirmasi",JOptionPane.YES_NO_OPTION);
        switch (getAnswer) {
            case 0:
                if (action=="Tambah") {
                    Customers c = new Customers((customerControl.lastCostumer() + 1), inputFirstName.getText(), inputLastName.getText(), inputEmail.getText(), inputPhoneNumber.getText(), inputAddress.getText());
                    Accounts a = new Accounts(0, accountTypeComboBox.getSelectedItem().toString(), Double.parseDouble(inputBalance.getText()), c, inputUsername.getText(), inputPassword.getText());
                    customerControl.insertCustomer(c);
                    accountControl.insertAccounts(a);
                }else{
                    Customers c = new Customers(selectedIdCustomer, inputFirstName.getText(), inputLastName.getText(), inputEmail.getText(), inputPhoneNumber.getText(), inputAddress.getText());
                    Accounts a = new Accounts(selectedIdAccount, accountTypeComboBox.getSelectedItem().toString(), Double.parseDouble(inputBalance.getText()), c, inputUsername.getText(), inputPassword.getText());
                    customerControl.updateCustomer(c);
                    accountControl.updateAccounts(a);
                }
                clearText();
                showAccounts();
                setComponent(false);
                setEditDeleteBtn(false);
                setAddBtn(true);
                break;
            case 1:
                //do nothing
                break;
            default:
                throw new AssertionError();
        }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void accountTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accountTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accountTypeComboBoxActionPerformed

    private void searchBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchBtnMouseClicked
        setComponent(false);
        TableAccounts accounts = accountControl.showTableAccounts(inputSearch.getText());
        if(accounts.getRowCount()==0){
                clearText();
                setEditDeleteBtn(false);
                inputSearch.setText("");
                JOptionPane.showMessageDialog(null,"Data tidak ditemukan!","Konfirmasi", JOptionPane.DEFAULT_OPTION);
            }else{
                tableCustomers.setModel(accounts);
            }
        clearText();
        inputSearch.setText("");
    }//GEN-LAST:event_searchBtnMouseClicked

    private void inputSearchMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_inputSearchMouseClicked
        setEditDeleteBtn(false);
    }//GEN-LAST:event_inputSearchMouseClicked

    private void inputFirstNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputFirstNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputFirstNameActionPerformed

    private void inputLastNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputLastNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputLastNameActionPerformed

    private void backgroundTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundTableMouseClicked

    private void inputPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputPasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputPasswordActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        int getAnswer = JOptionPane.showConfirmDialog(rootPane,
            "Apakah yakin ingin menghapus data?", "Konfirmasi",
            JOptionPane.YES_NO_OPTION);
        switch (getAnswer) {
            case 0:
            accountControl.deleteAccounts(selectedIdAccount);
            customerControl.deleteCustomer(selectedIdCustomer);
            clearText();
            showAccounts();
            setComponent(false);
            setEditDeleteBtn(false);
            setAddBtn(true);
            JOptionPane.showMessageDialog(null, " Data berhasil dihapus!");
            break;
            case 1:

            break;
            default:
            throw new AssertionError();
        }

    }//GEN-LAST:event_deleteBtnActionPerformed

    private void addBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBtnMouseClicked
        setComponent(true);
        setEditDeleteBtn(false);
        inputSearch.setText("");

        clearText();
        action = "Tambah";
    }//GEN-LAST:event_addBtnMouseClicked

    private void editBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editBtnMouseClicked
        setComponent(true);
        setEditDeleteBtn(false);
        inputSearch.setText("");
        action = "Tambah";
    }//GEN-LAST:event_editBtnMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CustomerServiceView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CustomerServiceView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> accountTypeComboBox;
    private javax.swing.JLabel accountTypeLabel;
    private javax.swing.JButton addBtn;
    private javax.swing.JLabel addressLabel;
    private view.PanelRound backgroundTable;
    private javax.swing.JLabel balanceLabel;
    private javax.swing.JPanel base;
    private view.PanelRound baseInputCus;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel firstNameLabel;
    private javax.swing.JTextField inputAddress;
    private javax.swing.JTextField inputBalance;
    private javax.swing.JTextField inputEmail;
    private javax.swing.JTextField inputFirstName;
    private javax.swing.JTextField inputLastName;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JTextField inputPhoneNumber;
    private javax.swing.JTextField inputSearch;
    private javax.swing.JTextField inputUsername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelAcc;
    private javax.swing.JLabel labelCus;
    private javax.swing.JLabel labelDelete1;
    private javax.swing.JLabel labelPane;
    private javax.swing.JLabel lastNameLabel;
    private javax.swing.JLabel password;
    private javax.swing.JLabel phoneNumberLabel;
    private javax.swing.JButton saveBtn;
    private view.PanelRound searchBtn;
    private javax.swing.JTable tableCustomers;
    private javaswingdev.swing.titlebar.TitleBar titleBar;
    private javax.swing.JLabel username;
    // End of variables declaration//GEN-END:variables
}
