/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view.employee;

/**
 *
 * @author riksi
 */
public class TellerTransferView extends javax.swing.JFrame {

    /**
     * Creates new form TellerTransferView
     */
    public TellerTransferView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        headerPane = new javax.swing.JPanel();
        labelPane = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        transferTable = new javax.swing.JTable();
        penerimaPanel = new view.PanelRound();
        cancelPenerimaBtn = new javax.swing.JButton();
        namaPenerimaInput = new javax.swing.JTextField();
        namaPenerimaLabel = new javax.swing.JLabel();
        noRekPenerimaInput = new javax.swing.JTextField();
        rekPenerimaLabel = new javax.swing.JLabel();
        penerimaLabel = new javax.swing.JLabel();
        okPenerimaBtn = new javax.swing.JButton();
        pengirimPanel = new view.PanelRound();
        cancelPengirimBtn = new javax.swing.JButton();
        namaPengirimInput = new javax.swing.JTextField();
        namaPengirimLabel = new javax.swing.JLabel();
        noRekPengirimInput = new javax.swing.JTextField();
        pengirimRekLabel = new javax.swing.JLabel();
        pengirimLabel = new javax.swing.JLabel();
        okPengirimBtn = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        transferPanel = new view.PanelRound();
        transferBtn = new javax.swing.JButton();
        jumlahTransferInput = new javax.swing.JTextField();
        jumlahTransferLabel = new javax.swing.JLabel();
        idTransferInput = new javax.swing.JTextField();
        idTransferLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setBackground(new java.awt.Color(225, 255, 177));
        base.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        base.setPreferredSize(new java.awt.Dimension(1650, 1080));

        headerPane.setBackground(new java.awt.Color(182, 227, 136));
        headerPane.setPreferredSize(new java.awt.Dimension(1650, 113));

        labelPane.setFont(new java.awt.Font("Poppins Medium", 0, 48)); // NOI18N
        labelPane.setForeground(new java.awt.Color(0, 0, 0));
        labelPane.setText("Transfer Transaction");

        javax.swing.GroupLayout headerPaneLayout = new javax.swing.GroupLayout(headerPane);
        headerPane.setLayout(headerPaneLayout);
        headerPaneLayout.setHorizontalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(labelPane)
                .addContainerGap(1098, Short.MAX_VALUE))
        );
        headerPaneLayout.setVerticalGroup(
            headerPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(headerPaneLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(labelPane)
                .addContainerGap(20, Short.MAX_VALUE))
        );

        transferTable.setAutoCreateRowSorter(true);
        transferTable.setBackground(new java.awt.Color(182, 227, 136));
        transferTable.setFont(new java.awt.Font("Poppins", 0, 14)); // NOI18N
        transferTable.setForeground(new java.awt.Color(0, 0, 0));
        transferTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(transferTable);

        penerimaPanel.setBackground(new java.awt.Color(182, 227, 136));
        penerimaPanel.setPreferredSize(new java.awt.Dimension(283, 194));
        penerimaPanel.setRoundBottomLeft(25);
        penerimaPanel.setRoundBottomRight(25);
        penerimaPanel.setRoundTopLeft(25);
        penerimaPanel.setRoundTopRight(25);

        cancelPenerimaBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelPenerimaBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cancelPenerimaBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelPenerimaBtn.setText("Cancel");

        namaPenerimaInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        namaPenerimaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        namaPenerimaLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPenerimaLabel.setText("Nama Penerima");

        noRekPenerimaInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        rekPenerimaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        rekPenerimaLabel.setForeground(new java.awt.Color(0, 0, 0));
        rekPenerimaLabel.setText("Nomor Rekening Penerima");

        penerimaLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        penerimaLabel.setForeground(new java.awt.Color(0, 0, 0));
        penerimaLabel.setText("Detail Penerima");

        okPenerimaBtn.setBackground(new java.awt.Color(13, 110, 253));
        okPenerimaBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        okPenerimaBtn.setForeground(new java.awt.Color(0, 0, 0));
        okPenerimaBtn.setText("OK");

        javax.swing.GroupLayout penerimaPanelLayout = new javax.swing.GroupLayout(penerimaPanel);
        penerimaPanel.setLayout(penerimaPanelLayout);
        penerimaPanelLayout.setHorizontalGroup(
            penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, penerimaPanelLayout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rekPenerimaLabel)
                    .addComponent(namaPenerimaLabel)
                    .addComponent(penerimaLabel)
                    .addComponent(cancelPenerimaBtn)
                    .addComponent(namaPenerimaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(penerimaPanelLayout.createSequentialGroup()
                        .addComponent(noRekPenerimaInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(okPenerimaBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(20, 20, 20))
        );
        penerimaPanelLayout.setVerticalGroup(
            penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(penerimaPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(penerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rekPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(penerimaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okPenerimaBtn)
                    .addComponent(noRekPenerimaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPenerimaLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPenerimaInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(cancelPenerimaBtn)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pengirimPanel.setBackground(new java.awt.Color(182, 227, 136));
        pengirimPanel.setPreferredSize(new java.awt.Dimension(303, 204));
        pengirimPanel.setRoundBottomLeft(25);
        pengirimPanel.setRoundBottomRight(25);
        pengirimPanel.setRoundTopLeft(25);
        pengirimPanel.setRoundTopRight(25);

        cancelPengirimBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelPengirimBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        cancelPengirimBtn.setForeground(new java.awt.Color(0, 0, 0));
        cancelPengirimBtn.setText("Cancel");

        namaPengirimInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        namaPengirimLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        namaPengirimLabel.setForeground(new java.awt.Color(0, 0, 0));
        namaPengirimLabel.setText("Nama Pengirim");

        noRekPengirimInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        pengirimRekLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        pengirimRekLabel.setForeground(new java.awt.Color(0, 0, 0));
        pengirimRekLabel.setText("Nomor Rekening Pengirim");

        pengirimLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        pengirimLabel.setForeground(new java.awt.Color(0, 0, 0));
        pengirimLabel.setText("Detail Pengirim");

        okPengirimBtn.setBackground(new java.awt.Color(13, 110, 253));
        okPengirimBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        okPengirimBtn.setForeground(new java.awt.Color(0, 0, 0));
        okPengirimBtn.setText("OK");

        javax.swing.GroupLayout pengirimPanelLayout = new javax.swing.GroupLayout(pengirimPanel);
        pengirimPanel.setLayout(pengirimPanelLayout);
        pengirimPanelLayout.setHorizontalGroup(
            pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengirimPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pengirimPanelLayout.createSequentialGroup()
                        .addComponent(noRekPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(okPengirimBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(pengirimPanelLayout.createSequentialGroup()
                        .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengirimRekLabel)
                            .addComponent(cancelPengirimBtn)
                            .addComponent(namaPengirimLabel)
                            .addComponent(pengirimLabel)
                            .addComponent(namaPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(67, 67, 67)))
                .addGap(14, 14, 14))
        );
        pengirimPanelLayout.setVerticalGroup(
            pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pengirimPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pengirimLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(pengirimRekLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pengirimPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(noRekPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(okPengirimBtn))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(namaPengirimLabel)
                .addGap(9, 9, 9)
                .addComponent(namaPengirimInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelPengirimBtn)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        jButton1.setBackground(new java.awt.Color(194, 16, 16));
        jButton1.setFont(new java.awt.Font("Poppins Medium", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        transferPanel.setBackground(new java.awt.Color(182, 227, 136));
        transferPanel.setPreferredSize(new java.awt.Dimension(210, 179));
        transferPanel.setRoundBottomLeft(20);
        transferPanel.setRoundBottomRight(20);
        transferPanel.setRoundTopLeft(20);
        transferPanel.setRoundTopRight(20);

        transferBtn.setBackground(new java.awt.Color(25, 135, 84));
        transferBtn.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N
        transferBtn.setForeground(new java.awt.Color(0, 0, 0));
        transferBtn.setText("Transfer");

        jumlahTransferInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        jumlahTransferLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        jumlahTransferLabel.setForeground(new java.awt.Color(0, 0, 0));
        jumlahTransferLabel.setText("Jumlah Transfer");

        idTransferInput.setFont(new java.awt.Font("Poppins Medium", 0, 12)); // NOI18N

        idTransferLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        idTransferLabel.setForeground(new java.awt.Color(0, 0, 0));
        idTransferLabel.setText("Transfer ID");

        javax.swing.GroupLayout transferPanelLayout = new javax.swing.GroupLayout(transferPanel);
        transferPanel.setLayout(transferPanelLayout);
        transferPanelLayout.setHorizontalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(transferPanelLayout.createSequentialGroup()
                                .addGroup(transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(idTransferLabel)
                                    .addComponent(jumlahTransferLabel))
                                .addGap(82, 82, 82))
                            .addComponent(jumlahTransferInput, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addComponent(idTransferInput, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(transferBtn, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap())
        );
        transferPanelLayout.setVerticalGroup(
            transferPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(transferPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idTransferLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(idTransferInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addComponent(jumlahTransferLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jumlahTransferInput, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(transferBtn)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(baseLayout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(penerimaPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 303, Short.MAX_VALUE)
                            .addComponent(pengirimPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(transferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(178, 178, 178))))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(headerPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pengirimPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 215, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(transferPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(penerimaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 501, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(78, 78, 78)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(332, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       TellerView tv = new TellerView();
       this.dispose();
       tv.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TellerTransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TellerTransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TellerTransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TellerTransferView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TellerTransferView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel base;
    private javax.swing.JButton cancelPenerimaBtn;
    private javax.swing.JButton cancelPengirimBtn;
    private javax.swing.JPanel headerPane;
    private javax.swing.JTextField idTransferInput;
    private javax.swing.JLabel idTransferLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField jumlahTransferInput;
    private javax.swing.JLabel jumlahTransferLabel;
    private javax.swing.JLabel labelPane;
    private javax.swing.JTextField namaPenerimaInput;
    private javax.swing.JLabel namaPenerimaLabel;
    private javax.swing.JTextField namaPengirimInput;
    private javax.swing.JLabel namaPengirimLabel;
    private javax.swing.JTextField noRekPenerimaInput;
    private javax.swing.JTextField noRekPengirimInput;
    private javax.swing.JButton okPenerimaBtn;
    private javax.swing.JButton okPengirimBtn;
    private javax.swing.JLabel penerimaLabel;
    private view.PanelRound penerimaPanel;
    private javax.swing.JLabel pengirimLabel;
    private view.PanelRound pengirimPanel;
    private javax.swing.JLabel pengirimRekLabel;
    private javax.swing.JLabel rekPenerimaLabel;
    private javax.swing.JButton transferBtn;
    private view.PanelRound transferPanel;
    private javax.swing.JTable transferTable;
    // End of variables declaration//GEN-END:variables
}
