
package view.admin;

import control.AdministratorsControl;
import control.EmployeesControl;
import exception.BlankInputException;
import java.awt.Cursor;
import java.awt.geom.RoundRectangle2D;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Administrators;
import model.Employees;
import view.LoginView;

public class DasboardView extends javax.swing.JFrame {
    private AdministratorsControl administratorsControl;
    private EmployeesControl employeesControl;
    private Administrators admin =null;
    String action = null;
    List<Administrators> listAdministrators;
    int selectedId = 0;
    List<Employees> listEmployees;
    
    public DasboardView(Administrators admin) {
        administratorsControl = new AdministratorsControl();
        employeesControl = new EmployeesControl();
        this.admin = admin;
        initComponents();
        helloText.setEditable(false);
        helloText.setText("Hello, Admin "+ this.admin.getUsername());
        totalAdminText.setEditable(false);
        totalEmpText.setEditable(false);
        showDashboard();
        totalAdminText.setText(String.valueOf(countTotalAdmin()));
        totalEmpText.setText(String.valueOf(countTotalEmployee()));
        init();
        initJFrame();
    }
    
    public void initJFrame(){
        setLocationRelativeTo(null);
        setShape(new RoundRectangle2D.Double(0, 0, getWidth(), getHeight(), 20, 20));
    }
    
    public void init(){
        titleBar.initJFram(this);
    }
    
    public void showDashboard(){
        adminTable.setModel(administratorsControl.showAdministrator(""));
         EmployeesTable.setModel(employeesControl.showEmployees(""));  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        base = new javax.swing.JPanel();
        kGradientPanel1 = new keeptoo.KGradientPanel();
        labelPane = new javax.swing.JLabel();
        titleBar = new javaswingdev.swing.titlebar.TitleBar();
        jLabel3 = new javax.swing.JLabel();
        leftSidePane = new javax.swing.JPanel();
        panelHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        panelAdmin = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        panelEmployee = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        logoutBtn = new javax.swing.JButton();
        backgroundInput2 = new view.PanelRound();
        helloText = new javax.swing.JTextField();
        backgroundInput3 = new view.PanelRound();
        totalAdminLabel = new javax.swing.JLabel();
        panelRound1 = new view.PanelRound();
        totalAdminText = new javax.swing.JTextField();
        totalEmpLabel = new javax.swing.JLabel();
        panelRound2 = new view.PanelRound();
        totalEmpText = new javax.swing.JTextField();
        backgroundInput4 = new view.PanelRound();
        jScrollPane2 = new javax.swing.JScrollPane();
        adminTable = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        labelCus = new javax.swing.JLabel();
        backgroundInput5 = new view.PanelRound();
        jScrollPane1 = new javax.swing.JScrollPane();
        EmployeesTable = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        labelCus1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        base.setBackground(new java.awt.Color(245, 245, 245));
        base.setPreferredSize(new java.awt.Dimension(1366, 720));

        kGradientPanel1.setkEndColor(new java.awt.Color(0, 73, 178));
        kGradientPanel1.setkGradientFocus(1000);
        kGradientPanel1.setkStartColor(new java.awt.Color(0, 149, 182));
        kGradientPanel1.setPreferredSize(new java.awt.Dimension(1440, 122));

        labelPane.setBackground(new java.awt.Color(255, 255, 255));
        labelPane.setFont(new java.awt.Font("Montserrat ExtraBold", 0, 48)); // NOI18N
        labelPane.setForeground(new java.awt.Color(255, 255, 255));
        labelPane.setText("Administrator");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/unauthorized-person.png"))); // NOI18N

        javax.swing.GroupLayout kGradientPanel1Layout = new javax.swing.GroupLayout(kGradientPanel1);
        kGradientPanel1.setLayout(kGradientPanel1Layout);
        kGradientPanel1Layout.setHorizontalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(kGradientPanel1Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(labelPane)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        kGradientPanel1Layout.setVerticalGroup(
            kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(kGradientPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(kGradientPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)
                        .addGap(24, 24, 24))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, kGradientPanel1Layout.createSequentialGroup()
                        .addComponent(titleBar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPane)
                        .addGap(20, 20, 20))))
        );

        leftSidePane.setBackground(new java.awt.Color(255, 255, 255));
        leftSidePane.setPreferredSize(new java.awt.Dimension(100, 1080));

        panelHome.setBackground(new java.awt.Color(245, 245, 245));
        panelHome.setBorder(javax.swing.BorderFactory.createMatteBorder(1, 5, 1, 0, new java.awt.Color(255, 183, 0)));
        panelHome.setPreferredSize(new java.awt.Dimension(114, 114));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/dashboard.png"))); // NOI18N

        javax.swing.GroupLayout panelHomeLayout = new javax.swing.GroupLayout(panelHome);
        panelHome.setLayout(panelHomeLayout);
        panelHomeLayout.setHorizontalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelHomeLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(25, 25, 25))
        );
        panelHomeLayout.setVerticalGroup(
            panelHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelHomeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));
        panelAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelAdminMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelAdminMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelAdminMouseExited(evt);
            }
        });

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/businessman.png"))); // NOI18N

        javax.swing.GroupLayout panelAdminLayout = new javax.swing.GroupLayout(panelAdmin);
        panelAdmin.setLayout(panelAdminLayout);
        panelAdminLayout.setHorizontalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelAdminLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4)
                .addGap(25, 25, 25))
        );
        panelAdminLayout.setVerticalGroup(
            panelAdminLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelAdminLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel4)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        panelEmployee.setBackground(new java.awt.Color(255, 255, 255));
        panelEmployee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                panelEmployeeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                panelEmployeeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                panelEmployeeMouseExited(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/manager.png"))); // NOI18N

        javax.swing.GroupLayout panelEmployeeLayout = new javax.swing.GroupLayout(panelEmployee);
        panelEmployee.setLayout(panelEmployeeLayout);
        panelEmployeeLayout.setHorizontalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelEmployeeLayout.setVerticalGroup(
            panelEmployeeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelEmployeeLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        logoutBtn.setBackground(new java.awt.Color(255, 0, 0));
        logoutBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-logout.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout leftSidePaneLayout = new javax.swing.GroupLayout(leftSidePane);
        leftSidePane.setLayout(leftSidePaneLayout);
        leftSidePaneLayout.setHorizontalGroup(
            leftSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelAdmin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(panelEmployee, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(leftSidePaneLayout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(9, Short.MAX_VALUE))
        );
        leftSidePaneLayout.setVerticalGroup(
            leftSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePaneLayout.createSequentialGroup()
                .addComponent(panelHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelAdmin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(panelEmployee, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 217, Short.MAX_VALUE)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18))
        );

        backgroundInput2.setBackground(new java.awt.Color(255, 255, 255));
        backgroundInput2.setPreferredSize(new java.awt.Dimension(285, 100));
        backgroundInput2.setRoundBottomLeft(20);
        backgroundInput2.setRoundBottomRight(20);
        backgroundInput2.setRoundTopLeft(20);
        backgroundInput2.setRoundTopRight(20);
        backgroundInput2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundInput2MouseClicked(evt);
            }
        });

        helloText.setBackground(new java.awt.Color(255, 255, 255));
        helloText.setFont(new java.awt.Font("Poppins Medium", 1, 30)); // NOI18N
        helloText.setForeground(new java.awt.Color(0, 0, 0));
        helloText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        helloText.setText("Hello Admin Ferdy");
        helloText.setBorder(null);
        helloText.setOpaque(true);
        helloText.setPreferredSize(new java.awt.Dimension(277, 40));
        helloText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                helloTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout backgroundInput2Layout = new javax.swing.GroupLayout(backgroundInput2);
        backgroundInput2.setLayout(backgroundInput2Layout);
        backgroundInput2Layout.setHorizontalGroup(
            backgroundInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundInput2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(helloText, javax.swing.GroupLayout.PREFERRED_SIZE, 382, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );
        backgroundInput2Layout.setVerticalGroup(
            backgroundInput2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundInput2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(helloText, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        backgroundInput3.setBackground(new java.awt.Color(255, 255, 255));
        backgroundInput3.setPreferredSize(new java.awt.Dimension(285, 100));
        backgroundInput3.setRoundBottomLeft(20);
        backgroundInput3.setRoundBottomRight(20);
        backgroundInput3.setRoundTopLeft(20);
        backgroundInput3.setRoundTopRight(20);
        backgroundInput3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundInput3MouseClicked(evt);
            }
        });

        totalAdminLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalAdminLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalAdminLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalAdminLabel.setText("Total Admin");

        panelRound1.setBackground(new java.awt.Color(255, 234, 210));
        panelRound1.setPreferredSize(new java.awt.Dimension(122, 56));
        panelRound1.setRoundBottomLeft(20);
        panelRound1.setRoundBottomRight(20);
        panelRound1.setRoundTopLeft(20);
        panelRound1.setRoundTopRight(20);

        totalAdminText.setEditable(false);
        totalAdminText.setBackground(new java.awt.Color(255, 234, 210));
        totalAdminText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalAdminText.setForeground(new java.awt.Color(0, 0, 0));
        totalAdminText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalAdminText.setText("10");
        totalAdminText.setBorder(null);
        totalAdminText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalAdminTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelRound1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(totalAdminText, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(totalAdminText, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE)
        );

        totalEmpLabel.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        totalEmpLabel.setForeground(new java.awt.Color(51, 51, 51));
        totalEmpLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        totalEmpLabel.setText("Total Employee");

        panelRound2.setBackground(new java.awt.Color(255, 234, 210));
        panelRound2.setPreferredSize(new java.awt.Dimension(122, 56));
        panelRound2.setRoundBottomLeft(20);
        panelRound2.setRoundBottomRight(20);
        panelRound2.setRoundTopLeft(20);
        panelRound2.setRoundTopRight(20);

        totalEmpText.setBackground(new java.awt.Color(255, 234, 210));
        totalEmpText.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        totalEmpText.setForeground(new java.awt.Color(0, 0, 0));
        totalEmpText.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        totalEmpText.setText("310");
        totalEmpText.setBorder(null);
        totalEmpText.setPreferredSize(new java.awt.Dimension(64, 26));
        totalEmpText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                totalEmpTextActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelRound2Layout = new javax.swing.GroupLayout(panelRound2);
        panelRound2.setLayout(panelRound2Layout);
        panelRound2Layout.setHorizontalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalEmpText, javax.swing.GroupLayout.DEFAULT_SIZE, 98, Short.MAX_VALUE)
                .addContainerGap())
        );
        panelRound2Layout.setVerticalGroup(
            panelRound2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(totalEmpText, javax.swing.GroupLayout.PREFERRED_SIZE, 15, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout backgroundInput3Layout = new javax.swing.GroupLayout(backgroundInput3);
        backgroundInput3.setLayout(backgroundInput3Layout);
        backgroundInput3Layout.setHorizontalGroup(
            backgroundInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundInput3Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(backgroundInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(totalEmpLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(backgroundInput3Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(backgroundInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(totalAdminLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(29, Short.MAX_VALUE))
        );
        backgroundInput3Layout.setVerticalGroup(
            backgroundInput3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundInput3Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(totalAdminLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound1, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(totalEmpLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelRound2, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        backgroundInput4.setBackground(new java.awt.Color(255, 255, 255));
        backgroundInput4.setPreferredSize(new java.awt.Dimension(285, 100));
        backgroundInput4.setRoundBottomLeft(20);
        backgroundInput4.setRoundBottomRight(20);
        backgroundInput4.setRoundTopLeft(20);
        backgroundInput4.setRoundTopRight(20);
        backgroundInput4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundInput4MouseClicked(evt);
            }
        });

        adminTable.setBackground(new java.awt.Color(152, 238, 204));
        adminTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(adminTable);

        jPanel1.setBackground(new java.awt.Color(255, 183, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        labelCus.setBackground(new java.awt.Color(51, 51, 51));
        labelCus.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        labelCus.setForeground(new java.awt.Color(0, 61, 121));
        labelCus.setText("Data Administrator");

        javax.swing.GroupLayout backgroundInput4Layout = new javax.swing.GroupLayout(backgroundInput4);
        backgroundInput4.setLayout(backgroundInput4Layout);
        backgroundInput4Layout.setHorizontalGroup(
            backgroundInput4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundInput4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(backgroundInput4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCus)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 547, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );
        backgroundInput4Layout.setVerticalGroup(
            backgroundInput4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, backgroundInput4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(labelCus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        backgroundInput5.setBackground(new java.awt.Color(255, 255, 255));
        backgroundInput5.setPreferredSize(new java.awt.Dimension(285, 100));
        backgroundInput5.setRoundBottomLeft(20);
        backgroundInput5.setRoundBottomRight(20);
        backgroundInput5.setRoundTopLeft(20);
        backgroundInput5.setRoundTopRight(20);
        backgroundInput5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                backgroundInput5MouseClicked(evt);
            }
        });

        EmployeesTable.setBackground(new java.awt.Color(152, 238, 204));
        EmployeesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(EmployeesTable);

        jPanel2.setBackground(new java.awt.Color(255, 183, 0));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 2, Short.MAX_VALUE)
        );

        labelCus1.setBackground(new java.awt.Color(51, 51, 51));
        labelCus1.setFont(new java.awt.Font("Montserrat ExtraBold", 1, 24)); // NOI18N
        labelCus1.setForeground(new java.awt.Color(0, 61, 121));
        labelCus1.setText("Data Employee");

        javax.swing.GroupLayout backgroundInput5Layout = new javax.swing.GroupLayout(backgroundInput5);
        backgroundInput5.setLayout(backgroundInput5Layout);
        backgroundInput5Layout.setHorizontalGroup(
            backgroundInput5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundInput5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(backgroundInput5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelCus1)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 548, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        backgroundInput5Layout.setVerticalGroup(
            backgroundInput5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundInput5Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(labelCus1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(12, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(leftSidePane, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(backgroundInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 436, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(backgroundInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addComponent(backgroundInput4, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(backgroundInput5, javax.swing.GroupLayout.PREFERRED_SIZE, 576, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(36, Short.MAX_VALUE))))
            .addComponent(kGradientPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 1366, Short.MAX_VALUE)
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(kGradientPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundInput3, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundInput2, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(27, 27, 27)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(backgroundInput5, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(backgroundInput4, javax.swing.GroupLayout.PREFERRED_SIZE, 358, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(leftSidePane, javax.swing.GroupLayout.PREFERRED_SIZE, 608, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(253, 253, 253))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    
    private int countTotalAdmin(){
        return administratorsControl.countAdmin();
    }
    private int countTotalEmployee(){
        return employeesControl.countEmployee();
    }
    private void helloTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_helloTextActionPerformed

    }//GEN-LAST:event_helloTextActionPerformed

    private void totalAdminTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalAdminTextActionPerformed
      
    }//GEN-LAST:event_totalAdminTextActionPerformed

    private void totalEmpTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_totalEmpTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_totalEmpTextActionPerformed

    private void panelAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminMouseClicked
        AdminManageView amv = new AdminManageView(admin);
        this.dispose();
        amv.setVisible(true);
    }//GEN-LAST:event_panelAdminMouseClicked

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginView lv = new LoginView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    private void backgroundInput2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundInput2MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundInput2MouseClicked

    private void backgroundInput3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundInput3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundInput3MouseClicked

    private void backgroundInput4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundInput4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundInput4MouseClicked

    private void backgroundInput5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_backgroundInput5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_backgroundInput5MouseClicked

    private void panelEmployeeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeMouseClicked
        EmployeeManageView ep = new EmployeeManageView(admin);
        this.dispose();
        ep.setVisible(true);
    }//GEN-LAST:event_panelEmployeeMouseClicked

    private void panelAdminMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminMouseEntered
        panelAdmin.setBackground(new java.awt.Color(245, 245, 245));
        panelAdmin.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }//GEN-LAST:event_panelAdminMouseEntered

    private void panelAdminMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelAdminMouseExited
        panelAdmin.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_panelAdminMouseExited

    private void panelEmployeeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeMouseEntered
        panelEmployee.setBackground(new java.awt.Color(245, 245, 245));
        panelEmployee.setCursor(new Cursor(Cursor.HAND_CURSOR) {
        });
    }//GEN-LAST:event_panelEmployeeMouseEntered

    private void panelEmployeeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_panelEmployeeMouseExited
        panelEmployee.setBackground(new java.awt.Color(255, 255, 255));
    }//GEN-LAST:event_panelEmployeeMouseExited

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DasboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DasboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DasboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DasboardView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DasboardView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable EmployeesTable;
    private javax.swing.JTable adminTable;
    private view.PanelRound backgroundInput2;
    private view.PanelRound backgroundInput3;
    private view.PanelRound backgroundInput4;
    private view.PanelRound backgroundInput5;
    private javax.swing.JPanel base;
    private javax.swing.JTextField helloText;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private keeptoo.KGradientPanel kGradientPanel1;
    private javax.swing.JLabel labelCus;
    private javax.swing.JLabel labelCus1;
    private javax.swing.JLabel labelPane;
    private javax.swing.JPanel leftSidePane;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JPanel panelAdmin;
    private javax.swing.JPanel panelEmployee;
    private javax.swing.JPanel panelHome;
    private view.PanelRound panelRound1;
    private view.PanelRound panelRound2;
    private javaswingdev.swing.titlebar.TitleBar titleBar;
    private javax.swing.JLabel totalAdminLabel;
    private javax.swing.JTextField totalAdminText;
    private javax.swing.JLabel totalEmpLabel;
    private javax.swing.JTextField totalEmpText;
    // End of variables declaration//GEN-END:variables
}
