
package view.admin;

import control.EmployeesControl;
import exception.BlankInputException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.TableModel;
import model.Employees;
import model.Administrators;
import view.LoginView;


public class EmployeeManageView extends javax.swing.JFrame {
    private EmployeesControl employeesControl;
    private Administrators admin;
    String action = null;
    List<Employees> listEmployees;
    int selectedId = 0;
    
    /**
     * Creates new form EmployeeManageView
     */
    public EmployeeManageView(Administrators admin) {
        initComponents();
        this.admin=admin;
        employeesControl = new EmployeesControl();
        setComponent(false);
        setEditDeleteBtn(false);
        showEmployees();
        
    }
    
    public void setComponent(boolean value){
        
        inputPane.setEnabled(value);
        rolePane.setEnabled(value);
        idInput.setEnabled(value);
        firstInput.setEnabled(value);
        lastInput.setEnabled(value);
        idLabel.setEnabled(value);
        firstLabel.setEnabled(value);
        lastLabel.setEnabled(value);
        
        
        userpassPane.setEnabled(value);
        passInput.setEnabled(value);
        userInput.setEnabled(value);
        passLabel.setEnabled(value);
        userLabel.setEnabled(value);
        
        startendPane.setEnabled(value);
        startInput.setEnabled(value);
        endInput.setEnabled(value);
        startLabel.setEnabled(value);
        endLabel.setEnabled(value);
        
        rolePane.setEnabled(value);
        tellerRadio.setEnabled(value);
        custumerRadio.setEnabled(value);
        roleLabel.setEnabled(value);
        
        
        stationOfficePane.setEnabled(value);
        stationInput.setEnabled(value);
        officeInput.setEnabled(value);
        stationLabel.setEnabled(value);
        officeLabel.setEnabled(value);
        
        saveBtn.setEnabled(value);
        cancelBtn.setEnabled(value);
    }
    
    public void setEditDeleteBtn(boolean value){
        editBtn.setEnabled(value);
        deleteBtn.setEnabled(value);
    }
    
    public void showEmployees(){
        employeeTable.setModel(employeesControl.showEmployees(""));
    }
    
    public void clearText(){
       idInput.setText("");
       firstInput.setText("");
       lastInput.setText("");
       passInput.setText("");
       userInput.setText("");
       startInput.setText("");
       endInput.setText("");
       stationInput.setText("");
       officeInput.setText("");
       tellerRadio.setSelected(false);
       custumerRadio.setSelected(false);
    }
    
    public void blankInputException() throws BlankInputException{
        if(tellerRadio.isSelected()){
            if(idInput.getText().isEmpty() || firstInput.getText().isEmpty() || lastInput.getText().isEmpty()
                || userInput.getText().isEmpty() || passInput.getText().isEmpty()
                || startInput.getText().isEmpty() || endInput.getText().isEmpty()
                || stationInput.getText().isEmpty()){
                throw new BlankInputException();
            }
        }else{
            if(idInput.getText().isEmpty() || firstInput.getText().isEmpty() || lastInput.getText().isEmpty()
                || userInput.getText().isEmpty() || passInput.getText().isEmpty()
                || startInput.getText().isEmpty() || endInput.getText().isEmpty()
                || officeInput.getText().isEmpty()){
                throw new BlankInputException();
            }
        }
    }
    
    public void blankRadioInputException() throws BlankInputException{
        if(tellerRadio.isSelected() || custumerRadio.isSelected()){
            throw new BlankInputException();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        roleBtnGroup = new javax.swing.ButtonGroup();
        base = new javax.swing.JPanel();
        leftSidePane = new javax.swing.JPanel();
        homePane = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        adminPane = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        EmployeePane = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        EmployeeBase = new javax.swing.JPanel();
        employeeLabel = new javax.swing.JLabel();
        btnPane = new javax.swing.JPanel();
        addBtn = new javax.swing.JButton();
        deleteBtn = new javax.swing.JButton();
        editBtn = new javax.swing.JButton();
        saveCancelPane = new javax.swing.JPanel();
        saveBtn = new javax.swing.JButton();
        cancelBtn = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        employeeTable = new javax.swing.JTable();
        inputPane = new javax.swing.JPanel();
        lastLabel = new javax.swing.JLabel();
        idLabel = new javax.swing.JLabel();
        lastInput = new javax.swing.JTextField();
        firstInput = new javax.swing.JTextField();
        firstLabel = new javax.swing.JLabel();
        idInput = new javax.swing.JTextField();
        userpassPane = new javax.swing.JPanel();
        userLabel = new javax.swing.JLabel();
        passInput = new javax.swing.JTextField();
        passLabel = new javax.swing.JLabel();
        userInput = new javax.swing.JTextField();
        startendPane = new javax.swing.JPanel();
        endInput = new javax.swing.JTextField();
        endLabel = new javax.swing.JLabel();
        startInput = new javax.swing.JTextField();
        startLabel = new javax.swing.JLabel();
        rolePane = new javax.swing.JPanel();
        roleLabel = new javax.swing.JLabel();
        tellerRadio = new javax.swing.JRadioButton();
        custumerRadio = new javax.swing.JRadioButton();
        logoutBtn = new javax.swing.JButton();
        stationOfficePane = new javax.swing.JPanel();
        officeInput = new javax.swing.JTextField();
        officeLabel = new javax.swing.JLabel();
        stationInput = new javax.swing.JTextField();
        stationLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        base.setBackground(new java.awt.Color(187, 187, 187));
        base.setPreferredSize(new java.awt.Dimension(1650, 1080));

        leftSidePane.setBackground(new java.awt.Color(140, 156, 152));
        leftSidePane.setPreferredSize(new java.awt.Dimension(100, 1080));

        homePane.setBackground(new java.awt.Color(255, 255, 255));
        homePane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homePaneMouseClicked(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/icons8-home-48.png"))); // NOI18N

        javax.swing.GroupLayout homePaneLayout = new javax.swing.GroupLayout(homePane);
        homePane.setLayout(homePaneLayout);
        homePaneLayout.setHorizontalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        homePaneLayout.setVerticalGroup(
            homePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(homePaneLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        adminPane.setBackground(new java.awt.Color(255, 255, 255));
        adminPane.setPreferredSize(new java.awt.Dimension(100, 92));
        adminPane.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                adminPaneMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/icons8-admin-64.png"))); // NOI18N

        javax.swing.GroupLayout adminPaneLayout = new javax.swing.GroupLayout(adminPane);
        adminPane.setLayout(adminPaneLayout);
        adminPaneLayout.setHorizontalGroup(
            adminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, adminPaneLayout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(17, 17, 17))
        );
        adminPaneLayout.setVerticalGroup(
            adminPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(adminPaneLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        EmployeePane.setBackground(new java.awt.Color(255, 255, 255));
        EmployeePane.setPreferredSize(new java.awt.Dimension(100, 92));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/admin/icons8-user-64.png"))); // NOI18N

        jPanel5.setBackground(new java.awt.Color(26, 119, 223));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 6, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout EmployeePaneLayout = new javax.swing.GroupLayout(EmployeePane);
        EmployeePane.setLayout(EmployeePaneLayout);
        EmployeePaneLayout.setHorizontalGroup(
            EmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeePaneLayout.createSequentialGroup()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addGap(29, 29, 29))
        );
        EmployeePaneLayout.setVerticalGroup(
            EmployeePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addContainerGap(22, Short.MAX_VALUE))
            .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout leftSidePaneLayout = new javax.swing.GroupLayout(leftSidePane);
        leftSidePane.setLayout(leftSidePaneLayout);
        leftSidePaneLayout.setHorizontalGroup(
            leftSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homePane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, leftSidePaneLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(leftSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(adminPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EmployeePane, javax.swing.GroupLayout.PREFERRED_SIZE, 100, Short.MAX_VALUE)))
        );
        leftSidePaneLayout.setVerticalGroup(
            leftSidePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(leftSidePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(homePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(adminPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EmployeePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(786, Short.MAX_VALUE))
        );

        EmployeeBase.setBackground(new java.awt.Color(140, 156, 152));

        employeeLabel.setFont(new java.awt.Font("Poppins Medium", 1, 40)); // NOI18N
        employeeLabel.setForeground(new java.awt.Color(0, 0, 0));
        employeeLabel.setText("Employee");

        javax.swing.GroupLayout EmployeeBaseLayout = new javax.swing.GroupLayout(EmployeeBase);
        EmployeeBase.setLayout(EmployeeBaseLayout);
        EmployeeBaseLayout.setHorizontalGroup(
            EmployeeBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EmployeeBaseLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(employeeLabel)
                .addContainerGap(1309, Short.MAX_VALUE))
        );
        EmployeeBaseLayout.setVerticalGroup(
            EmployeeBaseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, EmployeeBaseLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(employeeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );

        btnPane.setBackground(new java.awt.Color(187, 187, 187));

        addBtn.setBackground(new java.awt.Color(25, 135, 84));
        addBtn.setFont(new java.awt.Font("Century Gothic", 1, 17)); // NOI18N
        addBtn.setForeground(new java.awt.Color(255, 255, 255));
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-add.png"))); // NOI18N
        addBtn.setText("Tambah");
        addBtn.setBorder(null);
        addBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });

        deleteBtn.setBackground(new java.awt.Color(220, 53, 69));
        deleteBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        deleteBtn.setForeground(new java.awt.Color(255, 255, 255));
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-delete.png"))); // NOI18N
        deleteBtn.setText("Hapus");
        deleteBtn.setBorder(null);
        deleteBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });

        editBtn.setBackground(new java.awt.Color(241, 196, 15));
        editBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        editBtn.setForeground(new java.awt.Color(255, 255, 255));
        editBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-edit.png"))); // NOI18N
        editBtn.setText("Ubah");
        editBtn.setBorder(null);
        editBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout btnPaneLayout = new javax.swing.GroupLayout(btnPane);
        btnPane.setLayout(btnPaneLayout);
        btnPaneLayout.setHorizontalGroup(
            btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        btnPaneLayout.setVerticalGroup(
            btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(btnPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(btnPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(deleteBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        saveCancelPane.setBackground(new java.awt.Color(187, 187, 187));

        saveBtn.setBackground(new java.awt.Color(13, 110, 253));
        saveBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        saveBtn.setForeground(new java.awt.Color(255, 255, 255));
        saveBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-save.png"))); // NOI18N
        saveBtn.setText("Simpan");
        saveBtn.setBorder(null);
        saveBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        saveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveBtnActionPerformed(evt);
            }
        });

        cancelBtn.setBackground(new java.awt.Color(220, 53, 69));
        cancelBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        cancelBtn.setForeground(new java.awt.Color(255, 255, 255));
        cancelBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-cancel.png"))); // NOI18N
        cancelBtn.setText("Batal");
        cancelBtn.setBorder(null);
        cancelBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        cancelBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout saveCancelPaneLayout = new javax.swing.GroupLayout(saveCancelPane);
        saveCancelPane.setLayout(saveCancelPaneLayout);
        saveCancelPaneLayout.setHorizontalGroup(
            saveCancelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCancelPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        saveCancelPaneLayout.setVerticalGroup(
            saveCancelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(saveCancelPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(saveCancelPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(saveBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cancelBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        employeeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        employeeTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                employeeTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(employeeTable);

        inputPane.setBackground(new java.awt.Color(187, 187, 187));

        lastLabel.setBackground(new java.awt.Color(0, 0, 0));
        lastLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        lastLabel.setForeground(new java.awt.Color(0, 0, 0));
        lastLabel.setText("Last Name");

        idLabel.setBackground(new java.awt.Color(0, 0, 0));
        idLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        idLabel.setForeground(new java.awt.Color(0, 0, 0));
        idLabel.setText("ID Employee");

        lastInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastInputActionPerformed(evt);
            }
        });

        firstInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstInputActionPerformed(evt);
            }
        });

        firstLabel.setBackground(new java.awt.Color(0, 0, 0));
        firstLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        firstLabel.setForeground(new java.awt.Color(0, 0, 0));
        firstLabel.setText("First Name");

        idInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout inputPaneLayout = new javax.swing.GroupLayout(inputPane);
        inputPane.setLayout(inputPaneLayout);
        inputPaneLayout.setHorizontalGroup(
            inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastLabel)
                    .addGroup(inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(lastInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(idLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(firstLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(idInput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(firstInput, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        inputPaneLayout.setVerticalGroup(
            inputPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(inputPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(idLabel)
                .addGap(5, 5, 5)
                .addComponent(idInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(firstLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(firstInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lastInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        userpassPane.setBackground(new java.awt.Color(187, 187, 187));

        userLabel.setBackground(new java.awt.Color(0, 0, 0));
        userLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        userLabel.setForeground(new java.awt.Color(0, 0, 0));
        userLabel.setText("Username");

        passInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passInputActionPerformed(evt);
            }
        });

        passLabel.setBackground(new java.awt.Color(0, 0, 0));
        passLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        passLabel.setForeground(new java.awt.Color(0, 0, 0));
        passLabel.setText("Password");

        userInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userInputActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout userpassPaneLayout = new javax.swing.GroupLayout(userpassPane);
        userpassPane.setLayout(userpassPaneLayout);
        userpassPaneLayout.setHorizontalGroup(
            userpassPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpassPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(userpassPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(userLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(passLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(userInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                    .addComponent(passInput, javax.swing.GroupLayout.Alignment.LEADING))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        userpassPaneLayout.setVerticalGroup(
            userpassPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(userpassPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(userLabel)
                .addGap(5, 5, 5)
                .addComponent(userInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(passLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(passInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(96, 96, 96))
        );

        startendPane.setBackground(new java.awt.Color(187, 187, 187));

        endInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                endInputActionPerformed(evt);
            }
        });

        endLabel.setBackground(new java.awt.Color(0, 0, 0));
        endLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        endLabel.setForeground(new java.awt.Color(0, 0, 0));
        endLabel.setText("End Work Date");

        startInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                startInputActionPerformed(evt);
            }
        });

        startLabel.setBackground(new java.awt.Color(0, 0, 0));
        startLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        startLabel.setForeground(new java.awt.Color(0, 0, 0));
        startLabel.setText("Start Work Date");

        javax.swing.GroupLayout startendPaneLayout = new javax.swing.GroupLayout(startendPane);
        startendPane.setLayout(startendPaneLayout);
        startendPaneLayout.setHorizontalGroup(
            startendPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startendPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(startendPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(startendPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(startInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(endInput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(endLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(startLabel))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        startendPaneLayout.setVerticalGroup(
            startendPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(startendPaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(startLabel)
                .addGap(5, 5, 5)
                .addComponent(startInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(endLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(endInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        rolePane.setBackground(new java.awt.Color(187, 187, 187));

        roleLabel.setBackground(new java.awt.Color(0, 0, 0));
        roleLabel.setFont(new java.awt.Font("Poppins Medium", 1, 14)); // NOI18N
        roleLabel.setForeground(new java.awt.Color(0, 0, 0));
        roleLabel.setText("Role");

        roleBtnGroup.add(tellerRadio);
        tellerRadio.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        tellerRadio.setText("Teller");
        tellerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tellerRadioActionPerformed(evt);
            }
        });

        roleBtnGroup.add(custumerRadio);
        custumerRadio.setFont(new java.awt.Font("Poppins Medium", 0, 14)); // NOI18N
        custumerRadio.setText("Customer Service");
        custumerRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custumerRadioActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout rolePaneLayout = new javax.swing.GroupLayout(rolePane);
        rolePane.setLayout(rolePaneLayout);
        rolePaneLayout.setHorizontalGroup(
            rolePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(rolePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(roleLabel)
                    .addComponent(tellerRadio, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(custumerRadio))
                .addContainerGap())
        );
        rolePaneLayout.setVerticalGroup(
            rolePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(rolePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(roleLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tellerRadio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(custumerRadio)
                .addContainerGap())
        );

        logoutBtn.setBackground(new java.awt.Color(174, 74, 241));
        logoutBtn.setFont(new java.awt.Font("Century Gothic", 1, 18)); // NOI18N
        logoutBtn.setForeground(new java.awt.Color(255, 255, 255));
        logoutBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/buttons/icon-logout.png"))); // NOI18N
        logoutBtn.setText("Logout");
        logoutBtn.setBorder(null);
        logoutBtn.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        logoutBtn.setMaximumSize(new java.awt.Dimension(85, 23));
        logoutBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBtnActionPerformed(evt);
            }
        });

        stationOfficePane.setBackground(new java.awt.Color(187, 187, 187));

        officeInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                officeInputActionPerformed(evt);
            }
        });

        officeLabel.setBackground(new java.awt.Color(0, 0, 0));
        officeLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        officeLabel.setForeground(new java.awt.Color(0, 0, 0));
        officeLabel.setText("Office Number");

        stationInput.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stationInputActionPerformed(evt);
            }
        });

        stationLabel.setBackground(new java.awt.Color(0, 0, 0));
        stationLabel.setFont(new java.awt.Font("Poppins", 1, 14)); // NOI18N
        stationLabel.setForeground(new java.awt.Color(0, 0, 0));
        stationLabel.setText("Station Number");

        javax.swing.GroupLayout stationOfficePaneLayout = new javax.swing.GroupLayout(stationOfficePane);
        stationOfficePane.setLayout(stationOfficePaneLayout);
        stationOfficePaneLayout.setHorizontalGroup(
            stationOfficePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stationOfficePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(stationOfficePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(stationOfficePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(stationInput, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 270, Short.MAX_VALUE)
                        .addComponent(officeInput, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(officeLabel, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(stationLabel))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        stationOfficePaneLayout.setVerticalGroup(
            stationOfficePaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(stationOfficePaneLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(stationLabel)
                .addGap(5, 5, 5)
                .addComponent(stationInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(officeLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(officeInput, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout baseLayout = new javax.swing.GroupLayout(base);
        base.setLayout(baseLayout);
        baseLayout.setHorizontalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(leftSidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(EmployeeBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(baseLayout.createSequentialGroup()
                                .addComponent(inputPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(userpassPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(startendPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(baseLayout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(rolePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(28, 28, 28)
                                        .addComponent(stationOfficePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, baseLayout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(saveCancelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1393, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        baseLayout.setVerticalGroup(
            baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(leftSidePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(baseLayout.createSequentialGroup()
                .addComponent(EmployeeBase, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(12, 12, 12)
                .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userpassPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(startendPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(inputPane, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(63, 63, 63))
                    .addGroup(baseLayout.createSequentialGroup()
                        .addGroup(baseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(rolePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(stationOfficePane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(saveCancelPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)))
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 314, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addComponent(logoutBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 1558, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(base, javax.swing.GroupLayout.PREFERRED_SIZE, 880, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 6, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void adminPaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_adminPaneMouseClicked
        AdminManageView amv = new AdminManageView(admin);
        this.dispose();
        amv.setVisible(true);
    }//GEN-LAST:event_adminPaneMouseClicked

    private void homePaneMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homePaneMouseClicked
       DasboardView ds = new DasboardView(admin);
       this.dispose();
       ds.setVisible(true);
    }//GEN-LAST:event_homePaneMouseClicked

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
        // TODO add your handling code here:
        setEditDeleteBtn(false);
        setComponent(true);
        stationInput.setEnabled(false);
        officeInput.setEnabled(false);
        stationLabel.setEnabled(false);
        officeLabel.setEnabled(false);
        clearText();
        roleBtnGroup.clearSelection();
        idInput.setEditable(false);
        idInput.setText(String.valueOf(employeesControl.autoGenerateID()));
        action = "Add";
    }//GEN-LAST:event_addBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
        int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to delete data?", "Confirmation", JOptionPane.YES_NO_OPTION);
        if(getAnswer == 0){
            try{
                employeesControl.deleteEmployees(Integer.parseInt(idInput.getText()));
                clearText();
                setComponent(false);
                setEditDeleteBtn(false);
                addBtn.setEnabled(true);
                showEmployees();
                JOptionPane.showMessageDialog(this, "Successfully delete employee data");
            } catch(Exception e){
                System.out.println("Error deleting data...");
                System.out.println(e);
            }
        }
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void editBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editBtnActionPerformed
        // TODO add your handling code here:
        addBtn.setEnabled(false);
        deleteBtn.setEnabled(false);
        setComponent(true);
        stationInput.setEnabled(false);
        officeInput.setEnabled(false);
        stationLabel.setEnabled(false);
        officeLabel.setEnabled(false);
        idInput.setEnabled(false);
        action = "Change";
    }//GEN-LAST:event_editBtnActionPerformed

    private void saveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveBtnActionPerformed
                // TODO add your handling code here:
                try{
                        blankInputException();
                        if(action.equals("Add")){
                            int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to add employee?","Confirmation", JOptionPane.YES_NO_OPTION);
                            if(getAnswer == JOptionPane.YES_OPTION){
                                if(tellerRadio.isSelected()){
                                    Employees e = new Employees (Integer.parseInt(idInput.getText()), firstInput.getText(), lastInput.getText(), userInput.getText(), passInput.getText(),
                                        startInput.getText(), endInput.getText(), 1, officeInput.getText(), stationInput.getText());
                                    employeesControl.insertEmployees(e);
                                    JOptionPane.showMessageDialog(this, "Success to add employee");
                                }else{
                                    Employees e = new Employees (Integer.parseInt(idInput.getText()), firstInput.getText(), lastInput.getText(), userInput.getText(), passInput.getText(),
                                        startInput.getText(), endInput.getText(), 2, officeInput.getText(), stationInput.getText());
                                    employeesControl.insertEmployees(e);
                                    JOptionPane.showMessageDialog(this, "Success to add employee");
                                }
                            }else {
                                JOptionPane.showMessageDialog(this, "Failed to add employee");
                            }
                        }else{
                            int getAnswer = JOptionPane.showConfirmDialog(rootPane, "Are you sure want to change employee?","Confirmation", JOptionPane.YES_NO_OPTION);
                            if(getAnswer == JOptionPane.YES_OPTION){
                                if(tellerRadio.isSelected()){
                                    Employees e = new Employees (Integer.parseInt(idInput.getText()), firstInput.getText(), lastInput.getText(), userInput.getText(), passInput.getText(),
                                        startInput.getText(), endInput.getText(), 1, officeInput.getText(), stationInput.getText());
                                    employeesControl.updateEmployees(e);
                                    JOptionPane.showMessageDialog(this, "Success to change employee");
                                }else{
                                    Employees e = new Employees (Integer.parseInt(idInput.getText()), firstInput.getText(), lastInput.getText(), userInput.getText(), passInput.getText(),
                                        startInput.getText(), endInput.getText(), 2, officeInput.getText(), stationInput.getText());
                                    employeesControl.updateEmployees(e);
                                    JOptionPane.showMessageDialog(this, "Success to change employee");
                                }
                            }else {
                                JOptionPane.showMessageDialog(this, "Failed to change employee");
                            }
                        }
                        clearText();
                        setComponent(false);
                        setEditDeleteBtn(false);
                        roleBtnGroup.clearSelection();
                        showEmployees();
                    } catch(BlankInputException e){
                        JOptionPane.showConfirmDialog(null, "Input cannot be empty", "Warning", JOptionPane.DEFAULT_OPTION);
                        System.out.println("Error: " + e.toString());
                    }
    }//GEN-LAST:event_saveBtnActionPerformed

    private void cancelBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelBtnActionPerformed
        //        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(false);
        addBtn.setEnabled(true);
        showEmployees();
        clearText();
        roleBtnGroup.clearSelection();
    }//GEN-LAST:event_cancelBtnActionPerformed

    private void lastInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastInputActionPerformed

    private void firstInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstInputActionPerformed

    private void idInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idInputActionPerformed

    private void passInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passInputActionPerformed

    private void userInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userInputActionPerformed

    private void endInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_endInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_endInputActionPerformed

    private void startInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_startInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_startInputActionPerformed

    private void tellerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tellerRadioActionPerformed
        // TODO add your handling code here:
        officeInput.setEnabled(false);
        officeInput.setText("");
        stationInput.setEnabled(true);
        stationLabel.setEnabled(true);
        
    }//GEN-LAST:event_tellerRadioActionPerformed

    private void custumerRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custumerRadioActionPerformed
        // TODO add your handling code here:
        officeLabel.setEnabled(true);
        officeInput.setEnabled(true);
        stationInput.setEnabled(false);
       stationInput.setText("");
    }//GEN-LAST:event_custumerRadioActionPerformed

    private void employeeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_employeeTableMouseClicked
        // TODO add your handling code here:
        setComponent(false);
        setEditDeleteBtn(true);
        cancelBtn.setEnabled(true);
        int clickedRow = employeeTable.getSelectedRow();
        TableModel tableModel = employeeTable.getModel();

        idInput.setText(tableModel.getValueAt(clickedRow, 0).toString());
        firstInput.setText(tableModel.getValueAt(clickedRow, 3).toString());
        lastInput.setText(tableModel.getValueAt(clickedRow, 4).toString());
        passInput.setText(tableModel.getValueAt(clickedRow, 2).toString());
        userInput.setText(tableModel.getValueAt(clickedRow, 1).toString());
        startInput.setText(tableModel.getValueAt(clickedRow, 5).toString());
        endInput.setText(tableModel.getValueAt(clickedRow, 6).toString());
        if(tableModel.getValueAt(clickedRow, 7).toString().equals("Teller")){
            tellerRadio.setSelected(true);
        }else if(tableModel.getValueAt(clickedRow, 7).toString().equals("Customer Services")){
            custumerRadio.setSelected(true);
        }
        
        if(tellerRadio.isSelected()){
            stationInput.setText(tableModel.getValueAt(clickedRow, 8).toString());
            officeInput.setText("");
        }else{
            officeInput.setText(tableModel.getValueAt(clickedRow, 9).toString());
            stationInput.setText("");
        }
    }//GEN-LAST:event_employeeTableMouseClicked

    private void officeInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_officeInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_officeInputActionPerformed

    private void stationInputActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stationInputActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stationInputActionPerformed

    private void logoutBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBtnActionPerformed
        LoginView lv = new LoginView();
        this.dispose();
        lv.setVisible(true);
    }//GEN-LAST:event_logoutBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EmployeeManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EmployeeManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EmployeeManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EmployeeManageView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EmployeeManageView(null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EmployeeBase;
    private javax.swing.JPanel EmployeePane;
    private javax.swing.JButton addBtn;
    private javax.swing.JPanel adminPane;
    private javax.swing.JPanel base;
    private javax.swing.JPanel btnPane;
    private javax.swing.JButton cancelBtn;
    private javax.swing.JRadioButton custumerRadio;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JButton editBtn;
    private javax.swing.JLabel employeeLabel;
    private javax.swing.JTable employeeTable;
    private javax.swing.JTextField endInput;
    private javax.swing.JLabel endLabel;
    private javax.swing.JTextField firstInput;
    private javax.swing.JLabel firstLabel;
    private javax.swing.JPanel homePane;
    private javax.swing.JTextField idInput;
    private javax.swing.JLabel idLabel;
    private javax.swing.JPanel inputPane;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField lastInput;
    private javax.swing.JLabel lastLabel;
    private javax.swing.JPanel leftSidePane;
    private javax.swing.JButton logoutBtn;
    private javax.swing.JTextField officeInput;
    private javax.swing.JLabel officeLabel;
    private javax.swing.JTextField passInput;
    private javax.swing.JLabel passLabel;
    private javax.swing.ButtonGroup roleBtnGroup;
    private javax.swing.JLabel roleLabel;
    private javax.swing.JPanel rolePane;
    private javax.swing.JButton saveBtn;
    private javax.swing.JPanel saveCancelPane;
    private javax.swing.JTextField startInput;
    private javax.swing.JLabel startLabel;
    private javax.swing.JPanel startendPane;
    private javax.swing.JTextField stationInput;
    private javax.swing.JLabel stationLabel;
    private javax.swing.JPanel stationOfficePane;
    private javax.swing.JRadioButton tellerRadio;
    private javax.swing.JTextField userInput;
    private javax.swing.JLabel userLabel;
    private javax.swing.JPanel userpassPane;
    // End of variables declaration//GEN-END:variables
}
